# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Change timestamp'),
        ),
    ]
