# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pwd',
        ),
    ]
