# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20160628_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted', to='system.Team')),
            ],
        ),
        migrations.CreateModel(
            name='StoredFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, verbose_name='Token')),
                ('flag', models.CharField(max_length=24, verbose_name='Flag')),
            ],
        ),
        migrations.CreateModel(
            name='TeamService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_checks', models.IntegerField(verbose_name='Passed checks')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='service',
            name='uptime',
        ),
        migrations.AddField(
            model_name='service',
            name='bounty',
            field=models.PositiveIntegerField(default=0, verbose_name='Bug bounty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='fine',
            field=models.PositiveIntegerField(default=0, verbose_name='Vuln fine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='sup',
            field=models.PositiveIntegerField(default=0, verbose_name='Support cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamboxes', to='system.Service'),
        ),
        migrations.AddField(
            model_name='teamservice',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='system.Team'),
        ),
        migrations.AddField(
            model_name='storedflag',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='system.TeamService'),
        ),
        migrations.AddField(
            model_name='flagsubmit',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stolen_by', to='system.StoredFlag'),
        ),
    ]
