# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20160705_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreevent',
            name='delta',
            field=models.IntegerField(verbose_name='Points change'),
        ),
    ]
