# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20160705_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite',
            field=models.CharField(max_length=12, unique=True, verbose_name='Invite key'),
        ),
    ]
